In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
import autokeras as ak

In [12]:
dataset_path = '/content/drive/MyDrive/data_processed_20221127.csv'
df = pd.read_csv(dataset_path)
df

/content

,0,1,2,3,4,5,6,7,8,9,...,91.1,92.1,93.1,94.1,95.1,96.1,97.1,98.1,99.1,label
0,0.689634,0.683109,0.679447,0.678042,0.678290,0.679585,0.680740,0.682233,0.683152,0.682474,...,22.745190,22.778449,22.786214,22.714363,22.656942,22.614385,22.598164,22.632370,22.674052,0
1,0.687238,0.682719,0.680218,0.679290,0.679490,0.680374,0.681099,0.681889,0.682194,0.681311,...,22.482882,22.420708,22.348304,22.346509,22.362265,22.403190,22.462693,22.511563,22.557876,0
2,0.684247,0.685635,0.687400,0.689222,0.690785,0.691770,0.691096,0.688749,0.686682,0.685798,...,22.210150,22.152433,22.107722,22.140154,22.195555,22.273812,22.357330,22.420382,22.482802,0
3,0.688734,0.690477,0.691787,0.692646,0.693033,0.692929,0.691952,0.690001,0.689308,0.689491,...,21.726127,21.731574,21.736845,21.733976,21.723792,21.703144,21.663129,21.556924,21.518711,0
4,0.694636,0.690522,0.687323,0.684957,0.683338,0.682383,0.681943,0.682015,0.682821,0.683689,...,22.168144,22.121056,22.088400,22.127880,22.187291,22.267952,22.354049,22.426214,22.500300,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.713586,0.711215,0.704419,0.694665,0.683418,0.672144,0.664013,0.658173,0.654744,0.655969,...,21.759065,21.752640,21.794273,21.916704,22.036758,22.144680,22.218461,22.221820,22.250216,2
496,0.679653,0.677582,0.676992,0.677641,0.679289,0.681696,0.684711,0.687934,0.690916,0.693428,...,21.673035,21.588956,21.498905,21.436774,21.373163,21.313845,21.234477,21.208581,21.250695,2
497,0.709661,0.711982,0.712895,0.712768,0.711969,0.710865,0.710178,0.710519,0.710424,0.710287,...,21.966470,21.874637,21.773581,21.643489,21.560294,21.531109,21.559018,21.599654,21.598154,2
498,0.654670,0.656101,0.657234,0.658098,0.658725,0.659144,0.658938,0.658097,0.659006,0.660992,...,21.906505,21.841852,21.787866,21.852368,21.925160,21.996931,22.067393,22.080091,22.080742,2
499,0.718631,0.720300,0.720872,0.720647,0.719928,0.719017,0.717879,0.718947,0.720153,0.720463,...,22.042951,21.985944,21.931947,21.845070,21.767209,21.709035,21.693568,21.667797,21.616788,2

### Train Test Split

In [25]:
x = df.drop(columns=['label']).to_numpy()
y = df['label'].to_numpy()
train_x, test_x, train_y, test_y = train_test_split(x, y, random_state=0)
print("train: ", train_x.shape, train_y.shape)
print("test: ", test_x.shape, test_y.shape)

train:  (375, 200) (375,)
test:  (125, 200) (125,)

In [43]:
sdc = ak.StructuredDataClassifier(max_trials=10)
sdc.fit(x=train_x, y=train_y, epochs=10)

Epoch 1/10
12/12 [==============================] - 2s 12ms/step - loss: 0.6043 - accuracy: 0.7600
Epoch 2/10
12/12 [==============================] - 0s 13ms/step - loss: 0.3712 - accuracy: 0.8560
Epoch 3/10
12/12 [==============================] - 0s 11ms/step - loss: 0.3151 - accuracy: 0.8747
Epoch 4/10
12/12 [==============================] - 0s 11ms/step - loss: 0.2101 - accuracy: 0.9200
Epoch 5/10
12/12 [==============================] - 0s 8ms/step - loss: 0.1860 - accuracy: 0.9440
Epoch 6/10
12/12 [==============================] - 0s 8ms/step - loss: 0.1354 - accuracy: 0.9547
Epoch 7/10
12/12 [==============================] - 0s 14ms/step - loss: 0.0652 - accuracy: 0.9813
Epoch 8/10
12/12 [==============================] - 0s 11ms/step - loss: 0.0523 - accuracy: 0.9840
Epoch 9/10
12/12 [==============================] - 0s 7ms/step - loss: 0.0319 - accuracy: 0.9920
Epoch 10/10
12/12 [==============================] - 0s 7ms/step - loss: 0.0512 - accuracy: 0.9813

In [48]:
sdc.evaluate(test_x, test_y)

4/4 [==============================] - 1s 7ms/step - loss: 0.0831 - accuracy: 0.9840

[0.08307201415300369, 0.984000027179718]

In [49]:
model = sdc.export_model()
model.metrics_names

['loss', 'accuracy']

In [50]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 200)]             0

 multi_category_encoding (Mu  (None, 200)              0
 ltiCategoryEncoding)

 normalization (Normalizatio  (None, 200)              401
 n)

 dense (Dense)               (None, 256)               51456

 re_lu (ReLU)                (None, 256)               0

 dropout (Dropout)           (None, 256)               0

 dense_1 (Dense)             (None, 512)               131584

 re_lu_1 (ReLU)              (None, 512)               0

 dropout_1 (Dropout)         (None, 512)               0

 dense_2 (Dense)             (None, 32)                16416

 re_lu_2 (ReLU)              (None, 32)                0

 dropout_2 (Dropout)         (None, 32)                0

 dense_3 (Dense)             (None, 3)                 99

 classification_head_1 (Soft  (None, 3)                0
 max)

=================================================================
Total params: 199,956
Trainable params: 199,555
Non-trainable params: 401
_________________________________________________________________